#lang htdp/isl+

#| Exercise 441.
Evaluate (quick-sort< (list 10 6 8 9 14 12 3 11 14 16 2)) by hand.
Show only those lines that introduce a new recursive call to quick-sort<.
How many recursive applications of quick-sort< are required?
How many recursive applications of the append function? Suggest a general rule for a list of length n.
Evaluate (quick-sort< (list 1 2 3 4 5 6 7 8 9 10 11 12 13 14)) by hand.
How many recursive applications of quick-sort< are required?
How many recursive applications of append?
Does this contradict the first part of the exercise? 
|#

(quick-sort< (list 10 6 8 9 14 12 3 11 14 16 2))
==
(append (quick-sort< '(6 8 9 3 2))
        '(10)
        (quick-sort< '(14 12 11 14 16)))
==
(append (append (quick-sort< '(3 2))
                '(6)
                (quick-sort< '(8 9)))
        '(10)
        (append (quick-sort< '(12 11))
                '(14 14)
                (quick-sort< '(16))))
==
(append (append (append (quick-sort< '(2))
                        '(3)
                        (quick-sort< '()))
                '(6)
                (append (quick-sort< '())
                        '(8)
                        (quick-sort< '(9))))
        '(10)
        (append (append (quick-sort< '(11))
                        '(12)
                        (quick-sort< '()))
                '(14 14)
                (quick-sort< '(16))))
==
(append (append (append '(2)
                        '(3)
                        '())
                '(6)
                (append '()
                        '(8)
                        '(9)))
        '(10)
        (append (append '(11)
                        '(12)
                        '())
                '(14 14)
                '(16)))
==
'(2 3 6 8 9 10 11 12 14 14 16)

; 13 times
; 6 times

(quick-sort< (list 1 2 3 4 5 6 7 8 9 10 11 12 13 14))
==
(append (quick-sort< '())
        '(1)
        (quick-sort< '(2 3 4 5 6 7 8 9 10 11 12 13 14)))
==
(append (quick-sort< '())
        '(1)
        (append (quick-sort< '())
                '(2)
                (quick-sort< '(3 4 5 6 7 8 9 10 11 12 13 14))))
==
(append (quick-sort< '())
        '(1)
        (append (quick-sort< '())
                '(2)
                (append (quick-sort< '())
                        '(3)
                        (quick-sort< '(4 5 6 7 8 9 10 11 12 13 14)))))
==
(append (quick-sort< '())
        '(1)
        (append (quick-sort< '())
                '(2)
                (append (quick-sort< '())
                        '(3)
                        (append (quick-sort< '())
                                '(4)
                                (quick-sort< '(5 6 7 8 9 10 11 12 13 14))))))
==
(append (quick-sort< '())
        '(1)
        (append (quick-sort< '())
                '(2)
                (append (quick-sort< '())
                        '(3)
                        (append (quick-sort< '())
                                '(4)
                                (append (quick-sort< '())
                                        '(5)
                                        (quick-sort< '(6 7 8 9 10 11 12 13 14)))))))
==
(append (quick-sort< '())
        '(1)
        (append (quick-sort< '())
                '(2)
                (append (quick-sort< '())
                        '(3)
                        (append (quick-sort< '())
                                '(4)
                                (append (quick-sort< '())
                                        '(5)
                                        (append (quick-sort< '())
                                                '(6)
                                                (quick-sort< '(7 8 9 10 11 12 13 14))))))))
==
(append (quick-sort< '())
        '(1)
        (append (quick-sort< '())
                '(2)
                (append (quick-sort< '())
                        '(3)
                        (append (quick-sort< '())
                                '(4)
                                (append (quick-sort< '())
                                        '(5)
                                        (append (quick-sort< '())
                                                '(6)
                                                (append (quick-sort< '())
                                                        '(7)
                                                        (quick-sort< '(8 9 10 11 12 13 14)))))))))
==
(append (quick-sort< '())
        '(1)
        (append (quick-sort< '())
                '(2)
                (append (quick-sort< '())
                        '(3)
                        (append (quick-sort< '())
                                '(4)
                                (append (quick-sort< '())
                                        '(5)
                                        (append (quick-sort< '())
                                                '(6)
                                                (append (quick-sort< '())
                                                        '(7)
                                                        (append (quick-sort< '())
                                                                '(8)
                                                                (quick-sort< ' 9 10 11 12 13 14)))))))))
==
(append (quick-sort< '())
        '(1)
        (append (quick-sort< '())
                '(2)
                (append (quick-sort< '())
                        '(3)
                        (append (quick-sort< '())
                                '(4)
                                (append (quick-sort< '())
                                        '(5)
                                        (append (quick-sort< '())
                                                '(6)
                                                (append (quick-sort< '())
                                                        '(7)
                                                        (append (quick-sort< '())
                                                                '(8)
                                                                (append (quick-sort< '())
                                                                        '(9)
                                                                        (quick-sort< '(10 11 12 13 14)))))))))))
==
(append (quick-sort< '())
        '(1)
        (append (quick-sort< '())
                '(2)
                (append (quick-sort< '())
                        '(3)
                        (append (quick-sort< '())
                                '(4)
                                (append (quick-sort< '())
                                        '(5)
                                        (append (quick-sort< '())
                                                '(6)
                                                (append (quick-sort< '())
                                                        '(7)
                                                        (append (quick-sort< '())
                                                                '(8)
                                                                (append (quick-sort< '())
                                                                        '(9)
                                                                        (append (quick-sort< '())
                                                                                '(10)
                                                                                (quick-sort< '(11 12 13 14))))))))))))
==
(append (quick-sort< '())
        '(1)
        (append (quick-sort< '())
                '(2)
                (append (quick-sort< '())
                        '(3)
                        (append (quick-sort< '())
                                '(4)
                                (append (quick-sort< '())
                                        '(5)
                                        (append (quick-sort< '())
                                                '(6)
                                                (append (quick-sort< '())
                                                        '(7)
                                                        (append (quick-sort< '())
                                                                '(8)
                                                                (append (quick-sort< '())
                                                                        '(9)
                                                                        (append (quick-sort< '())
                                                                                '(10)
                                                                                (append (quick-sort< '())
                                                                                        '(11)
                                                                                        (quick-sort< '(12 13 14)))))))))))))
==
(append (quick-sort< '())
        '(1)
        (append (quick-sort< '())
                '(2)
                (append (quick-sort< '())
                        '(3)
                        (append (quick-sort< '())
                                '(4)
                                (append (quick-sort< '())
                                        '(5)
                                        (append (quick-sort< '())
                                                '(6)
                                                (append (quick-sort< '())
                                                        '(7)
                                                        (append (quick-sort< '())
                                                                '(8)
                                                                (append (quick-sort< '())
                                                                        '(9)
                                                                        (append (quick-sort< '())
                                                                                '(10)
                                                                                (append (quick-sort< '())
                                                                                        '(11)
                                                                                        (append (quick-sort< '())
                                                                                                '(12)
                                                                                                (quick-sort< '(13 14))))))))))))))
==
(append (quick-sort< '())
        '(1)
        (append (quick-sort< '())
                '(2)
                (append (quick-sort< '())
                        '(3)
                        (append (quick-sort< '())
                                '(4)
                                (append (quick-sort< '())
                                        '(5)
                                        (append (quick-sort< '())
                                                '(6)
                                                (append (quick-sort< '())
                                                        '(7)
                                                        (append (quick-sort< '())
                                                                '(8)
                                                                (append (quick-sort< '())
                                                                        '(9)
                                                                        (append (quick-sort< '())
                                                                                '(10)
                                                                                (append (quick-sort< '())
                                                                                        '(11)
                                                                                        (append (quick-sort< '())
                                                                                                '(12)
                                                                                                (append (quick-sort< '())
                                                                                                        '(13)
                                                                                                        (quick-sort< '(14)))))))))))))))
==
'(1 2 3 4 5 6 7 8 9 10 11 12 13 14)

; 28 times
; 13 times 